//package UserInterface;
//
//import DAO.FeeOperations;
//import Entities.Fee;
//import javax.swing.*;
//import javax.swing.table.DefaultTableModel;
//import java.sql.SQLException;
//import java.util.List;
//
///**
// *
// * @author karole
// */
//public class FeeDetailsUI extends javax.swing.JFrame {
//
//    /**
//     * Creates new form FeeDetails
//     */
//    public FeeDetailsUI() {
//        initComponents();
//        loadFeeDetails();
//    }
//    private void loadFeeDetails() {
//        try {
//            // Retrieve fee details from the database
//            List<Fee> feeList = FeeOperations.getFeeDetails();
//
//            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
//            model.setRowCount(0); // Clear any existing rows
//
//            // Create an instance of Fee to call the formatDate method
//            Fee fee = new Fee();
//
//            // Loop through each Fee object and add it to the table
//            for (Fee f : feeList) {
//                model.addRow(new Object[]{
//                        f.getFeeID(),
//                        f.getStudentID(),
//                        f.getAmount(),
//                        fee.formatDate(f.getDueDate()), // Format the due date before adding to the table
//                        f.getStatus(),
//                        f.getPaymentMethod(),
//                        fee.formatDate(f.getPaymentDate()) // Format the payment date before adding to the table
//                });
//            }
//        } catch (SQLException | ClassNotFoundException e) {
//            JOptionPane.showMessageDialog(this, "Error loading fee details: " + e.getMessage());
//        }
//    }
//
//
//    /**
//     * This method is called from within the constructor to initialize the form.
//     * WARNING: Do NOT modify this code. The content of this method is always
//     * regenerated by the Form Editor.
//     */
//    @SuppressWarnings("unchecked")
//    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
//    private void initComponents() {
//
//        jLabel1 = new javax.swing.JLabel();
//        jScrollPane1 = new javax.swing.JScrollPane();
//        jTable1 = new javax.swing.JTable();
//
//        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
//
//        jLabel1.setText("FEE STATUS DETAILS");
//
//        jTable1.setModel(new javax.swing.table.DefaultTableModel(
//            new Object [][] {
//                {null, null, null, null, null, null, null},
//                {null, null, null, null, null, null, null},
//                {null, null, null, null, null, null, null},
//                {null, null, null, null, null, null, null}
//            },
//            new String [] {
//                "Fee ID", "Amount", "Due Date", "Status", "Payment Method", "Payment Date", "Student ID"
//            }
//        ));
//        jScrollPane1.setViewportView(jTable1);
//
//        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
//        getContentPane().setLayout(layout);
//        layout.setHorizontalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
//                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addGap(292, 292, 292))
//            .addGroup(layout.createSequentialGroup()
//                .addGap(42, 42, 42)
//                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 811, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addContainerGap(35, Short.MAX_VALUE))
//        );
//        layout.setVerticalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(layout.createSequentialGroup()
//                .addGap(16, 16, 16)
//                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addGap(42, 42, 42)
//                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addContainerGap(62, Short.MAX_VALUE))
//        );
//
//        pack();
//    }// </editor-fold>//GEN-END:initComponents
//
//    public static void showDetails() {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FeeDetailsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FeeDetailsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FeeDetailsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FeeDetailsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FeeDetailsUI().setVisible(true);
//            }
//        });
//    }
//
//    // Variables declaration - do not modify//GEN-BEGIN:variables
//    private javax.swing.JLabel jLabel1;
//    private javax.swing.JScrollPane jScrollPane1;
//    private javax.swing.JTable jTable1;
//    // End of variables declaration//GEN-END:variables
//}

package UserInterface;


import DAO.FeeOperations;
import Entities.Fee;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.net.URL;
import java.sql.SQLException;
import java.util.List;


public class FeeDetailsUI extends JFrame {
    private JTable table;

    private void loadFeeDetails() {
        try {
            // Retrieve fee details from the database
            List<Fee> feeList = FeeOperations.getFeeDetails();

            DefaultTableModel model = (DefaultTableModel) table.getModel();
            model.setRowCount(0); // Clear existing rows

            // Instance to format dates
            Fee fee = new Fee();

            // Add rows to the table
            for (Fee f : feeList) {
                model.addRow(new Object[]{
                        f.getFeeID(),
                        f.getAmount(),
                        fee.formatDate(f.getDueDate()),
                        f.getStatus(),
                        f.getPaymentMethod(),
                        fee.formatDate(f.getPaymentDate()),
                        f.getStudentID()
                });
            }
        } catch (SQLException | ClassNotFoundException e) {
            JOptionPane.showMessageDialog(this, "Error loading fee details: " + e.getMessage());
        }
    }
    public FeeDetailsUI() {
        setTitle("Fee Status Details");
        setSize(1300, 700);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        // Load background image
        URL imageUrl = getClass().getResource("/UserInterface/h6.jpg");
        ImageIcon backgroundIcon = (imageUrl != null) ? new ImageIcon(imageUrl) : null;

        JLabel backgroundLabel = new JLabel();
        if (backgroundIcon != null) {
            backgroundLabel.setIcon(backgroundIcon);
        } else {
            backgroundLabel.setOpaque(true);
            backgroundLabel.setBackground(Color.LIGHT_GRAY);
        }

        setContentPane(backgroundLabel);
        backgroundLabel.setLayout(new GridBagLayout());

        // Create panel with table
        JPanel panel = new JPanel(new GridBagLayout());
        panel.setPreferredSize(new Dimension(1100, 500));
        panel.setBackground(new Color(245, 245, 245, 180)); // semi-transparent

        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(10, 10, 10, 10);

        // Title
        JLabel title = new JLabel("FEE STATUS DETAILS");
        title.setFont(new Font("Serif", Font.BOLD, 24));
        title.setForeground(new Color(60, 60, 60));
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridwidth = 2;
        panel.add(title, gbc);
        gbc.gridwidth = 1;

        // Table data
        String[] columnNames = {"Fee ID", "Amount", "Due Date", "Status", "Payment Method", "Payment Date", "Student ID"};
        Object[][] data = {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
               {null, null, null, null, null, null, null},
               {null, null, null, null, null, null, null}
        };


        table = new JTable(new DefaultTableModel(data, columnNames));
        table.setFont(new Font("Arial", Font.PLAIN, 14));
        table.setRowHeight(30);
        JScrollPane scrollPane = new JScrollPane(table);
        scrollPane.setPreferredSize(new Dimension(1000, 300));
        loadFeeDetails();
        gbc.gridy = 1;
        panel.add(scrollPane, gbc);

        backgroundLabel.add(panel);
        setVisible(true);
    }

    public void showDetails() {
        SwingUtilities.invokeLater(()->this.setVisible(true));
    }
}