//package UserInterface;
//import Services.LoginController;
//import javax.swing.JOptionPane;
//public class LoginUI extends javax.swing.JFrame {
//
//    /**
//     * Creates new form LoginUI
//     */
//    public LoginUI() {
//        initComponents();
//    }
//
//    /**
//     * This method is called from within the constructor to initialize the form.
//     * WARNING: Do NOT modify this code. The content of this method is always
//     * regenerated by the Form Editor.
//     */
//    @SuppressWarnings("unchecked")
//    // <editor-fold defaultstate="collapsed" desc="Generated Code">
//    private void initComponents() {
//
//        jLabel1 = new javax.swing.JLabel();
//        jLabel2 = new javax.swing.JLabel();
//        jLabel4 = new javax.swing.JLabel();
//        jTextField2 = new javax.swing.JTextField();
//        jTextField3 = new javax.swing.JTextField();
//        jToggleButton1 = new javax.swing.JToggleButton();
//        jToggleButton2 = new javax.swing.JToggleButton();
//        jToggleButton3 = new javax.swing.JToggleButton();
//        setPreferredSize(new java.awt.Dimension(1300,700));
//        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
//        setBackground(new java.awt.Color(0, 255, 204));
//
//        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
//        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
//        jLabel1.setText("REGISTRATION DETAILS");
//
//        jLabel2.setText("NAME");
//
//        jLabel4.setText("Password");
//
//        jTextField2.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jTextField2ActionPerformed(evt);
//            }
//        });
//
//        jToggleButton1.setText("Exit");
//        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jToggleButton1ActionPerformed(evt);
//            }
//        });
//
//        jToggleButton2.setText("Submit");
//        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jToggleButton2ActionPerformed(evt);
//            }
//        });
//
//        jToggleButton3.setText("Reset");
//        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jToggleButton3ActionPerformed(evt);
//            }
//        });
//
//        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
//        getContentPane().setLayout(layout);
//        layout.setHorizontalGroup(
//                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                        .addGroup(layout.createSequentialGroup()
//                                .addGap(24, 24, 24)
//                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
//                                        .addGroup(layout.createSequentialGroup()
//                                                .addComponent(jToggleButton2)
//                                                .addGap(85, 85, 85)
//                                                .addComponent(jToggleButton1)
//                                                .addGap(83, 83, 83)
//                                                .addComponent(jToggleButton3))
//                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
//                                                .addGroup(layout.createSequentialGroup()
//                                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
//                                                        .addGroup(layout.createSequentialGroup()
//                                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                                                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))))
//                                .addContainerGap(32, Short.MAX_VALUE))
//        );
//        layout.setVerticalGroup(
//                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                        .addGroup(layout.createSequentialGroup()
//                                .addContainerGap()
//                                .addComponent(jLabel1)
//                                .addGap(43, 43, 43)
//                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                                        .addComponent(jLabel2)
//                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                .addGap(74, 74, 74)
//                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                                        .addComponent(jLabel4)
//                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
//                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                                        .addComponent(jToggleButton1)
//                                        .addComponent(jToggleButton3)
//                                        .addComponent(jToggleButton2))
//                                .addGap(27, 27, 27))
//        );
//
//        pack();
//    }// </editor-fold>
//
//    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {
//        // TODO add your handling code here:
//    }
//
//    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {
//        // TODO add your handling code here:
//        System.exit(0);
//    }
//
//    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {
//        // TODO add your handling code here:
//
//        jTextField2.setText("");
//        jTextField3.setText("");
//    }
//
//    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {
//        // TODO add your handling code here:
//        String username= jTextField2.getText();
//        String password= jTextField3.getText();
//        //LoginController LC= new LoginController();
//        LoginController controller=new LoginController(this);
//        boolean B=controller.authenticate(username,password);
//        if (B== false){
//            JOptionPane.showMessageDialog(this, "Please enter correct username and password", "Invalid Login", JOptionPane.WARNING_MESSAGE);
//        }
//    }
//
//    public void LoginUimain() {
//
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new LoginUI().setVisible(true);
//            }
//        });
//    }
//
//    // Variables declaration - do not modify
//    private javax.swing.JLabel jLabel1;
//    private javax.swing.JLabel jLabel2;
//    private javax.swing.JLabel jLabel4;
//    private javax.swing.JTextField jTextField2;
//    private javax.swing.JTextField jTextField3;
//    private javax.swing.JToggleButton jToggleButton1;
//    private javax.swing.JToggleButton jToggleButton2;
//    private javax.swing.JToggleButton jToggleButton3;
//}


package UserInterface;

import Services.LoginController;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.URL;

public class LoginUI extends JFrame {
    private JPasswordField passwordField;
    private JTextField usernameField;

    public LoginUI() {
        setTitle("Login Page");
        setSize(1300, 700); // Match image dimensions
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        URL imageUrl = getClass().getResource("/UserInterface/h6.jpg");
        ImageIcon backgroundIcon = null;

        if (imageUrl != null) {
            backgroundIcon = new ImageIcon(imageUrl);
        } else {
            JOptionPane.showMessageDialog(this, "Background image not found.\nPlease ensure 'h6.jpg' is in the UI package.",
                    "Image Load Error", JOptionPane.WARNING_MESSAGE);
        }

        JLabel backgroundLabel = new JLabel();
        if (backgroundIcon != null) {
            backgroundLabel.setIcon(backgroundIcon);
        } else {
            backgroundLabel.setOpaque(true);
            backgroundLabel.setBackground(Color.LIGHT_GRAY);
        }

        setContentPane(backgroundLabel);
        backgroundLabel.setLayout(null); // Absolute layout for custom placement

        JPanel loginPanel = new JPanel();
        loginPanel.setLayout(null);
        loginPanel.setBounds(185, 120, 370, 420); // Manually positioned
        loginPanel.setBackground(new Color(120, 130, 140,120)); // Orange shade

        JLabel title = new JLabel("Login");
        title.setFont(new Font("Serif", Font.BOLD, 26));
        title.setBounds(140, 20, 200, 30);
        loginPanel.add(title);

        JLabel userLabel = new JLabel("Username");
        userLabel.setFont(new Font("Serif", Font.PLAIN, 18));
        userLabel.setBounds(40, 70, 100, 30);
        loginPanel.add(userLabel);

        usernameField = new JTextField();
        usernameField.setBounds(150, 70, 160, 30);
        loginPanel.add(usernameField);

        JLabel passLabel = new JLabel("Password");
        passLabel.setFont(new Font("Serif", Font.PLAIN, 18));
        passLabel.setBounds(40, 120, 100, 30);
        loginPanel.add(passLabel);

        passwordField = new JPasswordField();
        passwordField.setBounds(150, 120, 160, 30);
        loginPanel.add(passwordField);

        JCheckBox showPassword = new JCheckBox("Show password");
        showPassword.setBackground(new Color(255, 174, 0));
        showPassword.setBounds(150, 160, 150, 30);
        showPassword.setFont(new Font("Arial", Font.PLAIN, 14));
        showPassword.addActionListener(e -> {
            passwordField.setEchoChar(showPassword.isSelected() ? (char) 0 : '*');
        });
        loginPanel.add(showPassword);

        JButton resetButton = createFlatButton("Reset");
        resetButton.setBounds(50, 220, 100, 35);
        resetButton.addActionListener(e -> handleReset(usernameField));
        loginPanel.add(resetButton);

        JButton loginButton = createFlatButton("Login");
        loginButton.setBounds(200, 220, 100, 35);
        loginButton.addActionListener(this::handleSubmit);
        loginPanel.add(loginButton);

        JButton exitButton = createFlatButton("Exit");
        exitButton.setBounds(125, 280, 100, 35);
        exitButton.addActionListener(e -> System.exit(0));
        loginPanel.add(exitButton);

        backgroundLabel.add(loginPanel);
        setVisible(true);
    }

    private JButton createFlatButton(String text) {
        JButton button = new JButton(text);
        button.setBackground(Color.WHITE);
        button.setForeground(Color.BLACK);
        button.setFocusPainted(false);
        button.setFont(new Font("Arial", Font.BOLD, 14));
        button.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        return button;
    }
    //    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {
//        // TODO add your handling code here:
//        String username= jTextField2.getText();
//        String password= jTextField3.getText();
//        //LoginController LC= new LoginController();
//        LoginController controller=new LoginController(this);
//        boolean B=controller.authenticate(username,password);
//        if (B== false){
//            JOptionPane.showMessageDialog(this, "Please enter correct username and password", "Invalid Login", JOptionPane.WARNING_MESSAGE);
//        }
//    }
    private void handleSubmit(ActionEvent e) {
        String username = usernameField.getText();
        String password = new String(passwordField.getPassword());

        // LoginController call
        LoginController controller = new LoginController(this);
        boolean isAuthenticated = controller.authenticate(username, password);

        if (isAuthenticated== false){
            JOptionPane.showMessageDialog(this, "Please enter correct username and password", "Invalid Login", JOptionPane.WARNING_MESSAGE);
        }
    }

    private void handleReset(JTextField usernameField) {
        usernameField.setText("");
        passwordField.setText("");
    }

    public void LoginUimain() {
        SwingUtilities.invokeLater(() -> setVisible(true));
    }
}