//
//package UserInterface;
//import DAO.RoomOperations;
//import Entities.Student;
//import Services.WardenController;
//
//import javax.swing.*;
//import java.util.List;
//
//public class NewStudent extends javax.swing.JFrame {
//
//    /**
//     * Creates new form NewStudent
//     */
//    public NewStudent() {
//        initComponents();
//        populateRoomDropdown();
//    }
//    private void populateRoomDropdown() {
//        RoomOperations roomOps = new RoomOperations();
//        List<String> availableRooms = roomOps.fetchAvailableRooms();
//
//        // Clear the current items in the dropdown
//        choice1.removeAll();
//
//        // Add available rooms to the dropdown
//        for (String roomNo : availableRooms) {
//            choice1.add(roomNo);
//        }
//    }
//    /**
//     * This method is called from within the constructor to initialize the form.
//     * WARNING: Do NOT modify this code. The content of this method is always
//     * regenerated by the Form Editor.
//     */
//    @SuppressWarnings("unchecked")
//    // <editor-fold defaultstate="collapsed" desc="Generated Code">
//    private void initComponents() {
//
//        jLabel2 = new javax.swing.JLabel();
//        jLabel1 = new javax.swing.JLabel();
//        jLabel3 = new javax.swing.JLabel();
//        jLabel4 = new javax.swing.JLabel();
//        jLabel5 = new javax.swing.JLabel();
//        jLabel6 = new javax.swing.JLabel();
//        jLabel7 = new javax.swing.JLabel();
//        jLabel8 = new javax.swing.JLabel();
//        jSeparator1 = new javax.swing.JSeparator();
//        jLabel9 = new javax.swing.JLabel();
//        jTextField1 = new javax.swing.JTextField();
//        jTextField2 = new javax.swing.JTextField();
//        jTextField3 = new javax.swing.JTextField();
//        jTextField4 = new javax.swing.JTextField();
//        jTextField5 = new javax.swing.JTextField();
//        jTextField6 = new javax.swing.JTextField();
//        jTextField7 = new javax.swing.JTextField();
//        jButton1 = new javax.swing.JButton();
//        jButton2 = new javax.swing.JButton();
//        choice1 = new java.awt.Choice();
//        jLabel10 = new javax.swing.JLabel();
//        jPasswordField1 = new javax.swing.JPasswordField();
//
//        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
//        setPreferredSize(new java.awt.Dimension(694, 488));
//
//        jLabel2.setFont(new java.awt.Font("Segoe UserInterface", 1, 18)); // NOI18N
//        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
//        jLabel2.setText("ADD NEW STUDENT");
//        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
//
//
//
//        jLabel1.setText("Name");
//
//        jLabel3.setText("Unique Id(aadhar)");
//
//        jLabel4.setText("Gender");
//
//        jLabel5.setText("Date of birth");
//
//        jLabel6.setText("Admission Date");
//
//        jLabel7.setText("Contact Number");
//
//        jLabel8.setText("Address");
//
//        jLabel9.setText("Room number ");
//
//        jTextField1.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jTextField1ActionPerformed(evt);
//            }
//        });
//
//        jTextField4.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jTextField4ActionPerformed(evt);
//            }
//        });
//
//        jTextField6.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jTextField6ActionPerformed(evt);
//            }
//        });
//
//        jButton1.setText("Submit");
//        jButton1.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jButton1ActionPerformed(evt);
//            }
//        });
//
//        jButton2.setText("Reset");
//        jButton2.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jButton2ActionPerformed(evt);
//            }
//        });
//
//        jLabel10.setText("Set new password");
//
//        jPasswordField1.setText("jPasswordField1");
//        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jPasswordField1ActionPerformed(evt);
//            }
//        });
//
//        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
//        getContentPane().setLayout(layout);
//        layout.setHorizontalGroup(
//                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 695, Short.MAX_VALUE)
//                        .addGroup(layout.createSequentialGroup()
//                                .addComponent(jSeparator1)
//                                .addContainerGap())
//                        .addGroup(layout.createSequentialGroup()
//                                .addGap(35, 35, 35)
//                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
//                                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
//                                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//                                        .addGroup(layout.createSequentialGroup()
//                                                .addComponent(jButton1)
//                                                .addGap(18, 18, 18)
//                                                .addComponent(jButton2))
//                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
//                                        .addComponent(jTextField1)
//                                        .addComponent(jTextField2)
//                                        .addComponent(jTextField3)
//                                        .addComponent(jTextField4)
//                                        .addComponent(jTextField5)
//                                        .addComponent(jTextField6)
//                                        .addComponent(jTextField7, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
//                                        .addComponent(choice1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                                        .addComponent(jPasswordField1))
//                                .addGap(38, 38, 38))
//        );
//        layout.setVerticalGroup(
//                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                        .addGroup(layout.createSequentialGroup()
//                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                .addGap(27, 27, 27)
//                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                                        .addComponent(jLabel1)
//                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                .addGap(18, 18, 18)
//                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                                        .addComponent(jLabel3)
//                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                .addGap(18, 18, 18)
//                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                .addGap(18, 18, 18)
//                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                .addGap(18, 18, 18)
//                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                .addGap(22, 22, 22)
//                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                .addGap(18, 18, 18)
//                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                                        .addComponent(jLabel8)
//                                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                .addGap(18, 18, 18)
//                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                        .addComponent(jLabel9)
//                                        .addComponent(choice1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                .addGap(18, 18, 18)
//                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                        .addComponent(jLabel10)
//                                        .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
//                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                                        .addComponent(jButton1)
//                                        .addComponent(jButton2))
//                                .addContainerGap())
//        );
//
//        pack();
//    }// </editor-fold>
//
//    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//        // TODO add your handling code here:
//        String name,id,gender,DOB,date_of_admission,contact_number,address,password;
//        name=jTextField1.getText();
//        id=jTextField2.getText();
//        gender=jTextField3.getText();
//        DOB=jTextField4.getText();
//        date_of_admission=jTextField5.getText();
//        contact_number=jTextField6.getText();
//        address=jTextField7.getText();
//        password=jPasswordField1.getText();
//
//        String selectedRoom = choice1.getSelectedItem();
//        // Create a new Student object
//        Student student = new Student(name, id, gender, DOB, date_of_admission, contact_number, address,password,selectedRoom);
//        WardenController.addNewStudent(student,this);
//
//    }
//
//    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
//        // TODO add your handling code here:
//        jTextField1.setText("");
//        jTextField2.setText("");
//        jTextField3.setText("");
//        jTextField4.setText("");
//        jTextField5.setText("");
//        jTextField6.setText("");
//        jTextField7.setText("");
//
//    }
//
//    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {
//        // TODO add your handling code here:
//    }
//
//    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {
//        // TODO add your handling code here:
//    }
//
//    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {
//        // TODO add your handling code here:
//    }
//
//    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {
//        // TODO add your handling code here:
//    }
//
//    /**
//     */
//    public void openEnrollStudent() {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(NewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(NewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(NewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(NewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new NewStudent().setVisible(true);
//            }
//        });
//    }
//
//    // Variables declaration - do not modify
//    private java.awt.Choice choice1;
//    private javax.swing.JButton jButton1;
//    private javax.swing.JButton jButton2;
//    private javax.swing.JLabel jLabel1;
//    private javax.swing.JLabel jLabel10;
//    private javax.swing.JLabel jLabel2;
//    private javax.swing.JLabel jLabel3;
//    private javax.swing.JLabel jLabel4;
//    private javax.swing.JLabel jLabel5;
//    private javax.swing.JLabel jLabel6;
//    private javax.swing.JLabel jLabel7;
//    private javax.swing.JLabel jLabel8;
//    private javax.swing.JLabel jLabel9;
//    private javax.swing.JPasswordField jPasswordField1;
//    private javax.swing.JSeparator jSeparator1;
//    private javax.swing.JTextField jTextField1;
//    private javax.swing.JTextField jTextField2;
//    private javax.swing.JTextField jTextField3;
//    private javax.swing.JTextField jTextField4;
//    private javax.swing.JTextField jTextField5;
//    private javax.swing.JTextField jTextField6;
//    private javax.swing.JTextField jTextField7;
//    // End of variables declaration
//}



//package UserInterface;
//
//import javax.swing.*;
//import java.awt.*;
//import java.awt.event.ActionEvent;
//import java.net.URL;
//
//public class NewStudent extends JFrame {
//
//    private JTextField nameField, aadharField, mobileField, dobField, admissionDateField, genderField, passwordField, roomField;
//    private JTextArea addressArea;
//
//    public NewStudent() {
//        setTitle("Add New Student");
//        setSize(1300, 700);
//        setLocationRelativeTo(null);
//        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
//
//        // Load background image
//        URL imageUrl = getClass().getResource("/UserInterface/h6.jpg");
//        ImageIcon backgroundIcon = (imageUrl != null) ? new ImageIcon(imageUrl) : null;
//
//        JLabel backgroundLabel = new JLabel();
//        if (backgroundIcon != null) {
//            backgroundLabel.setIcon(backgroundIcon);
//        } else {
//            backgroundLabel.setOpaque(true);
//            backgroundLabel.setBackground(Color.LIGHT_GRAY);
//        }
//
//        setContentPane(backgroundLabel);
//        backgroundLabel.setLayout(new GridBagLayout());
//
//        // Center form panel
//        JPanel formPanel = new JPanel();
//        formPanel.setPreferredSize(new Dimension(550, 600));
//        formPanel.setLayout(new GridBagLayout());
//        formPanel.setBackground(new Color(245, 245, 245,160)); // Light grey
//
//        GridBagConstraints gbc = new GridBagConstraints();
//        gbc.insets = new Insets(10, 10, 10, 10);
//        gbc.anchor = GridBagConstraints.WEST;
//
//        // Title
//        JLabel titleLabel = new JLabel("Add New Student");
//        titleLabel.setFont(new Font("Serif", Font.BOLD, 24));
//        titleLabel.setForeground(new Color(60, 60, 60));
//        gbc.gridwidth = 2;
//        gbc.gridx = 0;
//        gbc.gridy = 0;
//        formPanel.add(titleLabel, gbc);
//        gbc.gridwidth = 1;
//
//        int row = 1;
//        nameField = addRow("Name", row++, formPanel, gbc);
//        aadharField = addRow("Aadhar No.", row++, formPanel, gbc);
//        mobileField = addRow("Mobile No.", row++, formPanel, gbc);
//        dobField = addRow("DOB", row++, formPanel, gbc);
//
//        // Address (textarea)
//        gbc.gridx = 0;
//        gbc.gridy = row;
//        JLabel addressLabel = new JLabel("Address");
//        addressLabel.setFont(new Font("Arial", Font.BOLD, 16));
//        addressLabel.setForeground(Color.DARK_GRAY);
//        formPanel.add(addressLabel, gbc);
//
//        gbc.gridx = 1;
//        addressArea = new JTextArea();
//        addressArea.setFont(new Font("Arial", Font.PLAIN, 15));
//        addressArea.setLineWrap(true);
//        addressArea.setWrapStyleWord(true);
//        JScrollPane scrollPane = new JScrollPane(addressArea);
//        scrollPane.setPreferredSize(new Dimension(250, 60));
//        formPanel.add(scrollPane, gbc);
//        row++;
//
//        admissionDateField = addRow("Admission Date", row++, formPanel, gbc);
//        genderField = addRow("Gender", row++, formPanel, gbc);
//        passwordField = addRow("Set Password", row++, formPanel, gbc);
//        roomField = addRow("Room No.", row++, formPanel, gbc);
//
//        // Buttons
//        gbc.gridx = 0;
//        gbc.gridy = row;
//        JButton resetBtn = createStyledButton("Reset", this::resetForm);
//        formPanel.add(resetBtn, gbc);
//
//        gbc.gridx = 1;
//        JButton submitBtn = createStyledButton("Submit", this::handleSubmit);
//        formPanel.add(submitBtn, gbc);
//
//        backgroundLabel.add(formPanel);
//        setVisible(true);
//    }
//
//    private JTextField addRow(String label, int row, JPanel panel, GridBagConstraints gbc) {
//        JLabel jLabel = new JLabel(label);
//        jLabel.setFont(new Font("Arial", Font.BOLD, 16));
//        jLabel.setForeground(Color.DARK_GRAY);
//
//        JTextField textField = new JTextField();
//        textField.setFont(new Font("Arial", Font.PLAIN, 15));
//        textField.setPreferredSize(new Dimension(250, 30));
//
//        gbc.gridx = 0;
//        gbc.gridy = row;
//        panel.add(jLabel, gbc);
//
//        gbc.gridx = 1;
//        panel.add(textField, gbc);
//
//        return textField;
//    }
//
//    private JButton createStyledButton(String text, java.awt.event.ActionListener listener) {
//        JButton button = new JButton(text);
//        button.setFont(new Font("Arial", Font.BOLD, 14));
//        button.setBackground(new Color(255, 140, 0));
//        button.setForeground(Color.ORANGE);
//        button.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
//        button.setFocusPainted(false);
//        button.setBorder(BorderFactory.createEmptyBorder(10, 20, 10, 20));
//        button.addActionListener(listener);
//        return button;
//    }
//
//    private void resetForm(ActionEvent e) {
//        nameField.setText("");
//        aadharField.setText("");
//        mobileField.setText("");
//        dobField.setText("");
//        addressArea.setText("");
//        admissionDateField.setText("");
//        genderField.setText("");
//        passwordField.setText("");
//        roomField.setText("");
//    }
//    //    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
////        // TODO add your handling code here:
////        String name,id,gender,DOB,date_of_admission,contact_number,address,password;
////        name=jTextField1.getText();
////        id=jTextField2.getText();
////        gender=jTextField3.getText();
////        DOB=jTextField4.getText();
////        date_of_admission=jTextField5.getText();
////        contact_number=jTextField6.getText();
////        address=jTextField7.getText();
////        password=jPasswordField1.getText();
////
////        String selectedRoom = choice1.getSelectedItem();
////        // Create a new Student object
////        Student student = new Student(name, id, gender, DOB, date_of_admission, contact_number, address,password,selectedRoom);
////        WardenController.addNewStudent(student,this);
////
////    }
//    private void handleSubmit(ActionEvent e) {
//        if (nameField.getText().trim().isEmpty() ||
//                aadharField.getText().trim().isEmpty() ||
//                mobileField.getText().trim().isEmpty() ||
//                dobField.getText().trim().isEmpty() ||
//                addressArea.getText().trim().isEmpty() ||
//                admissionDateField.getText().trim().isEmpty() ||
//                genderField.getText().trim().isEmpty() ||
//                passwordField.getText().trim().isEmpty() ||
//                roomField.getText().trim().isEmpty()) {
//
//            JOptionPane.showMessageDialog(this, "Please fill in all the fields.", "Validation Error", JOptionPane.WARNING_MESSAGE);
//            return;
//        }
//
//        // Success message (You can add DB/file logic here)
//        JOptionPane.showMessageDialog(this, "Student information submitted successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
//        resetForm(e);
//    }
//
//    public void openEnrollStudent() {
//        SwingUtilities.invokeLater(() -> this.setVisible(true));
//    }
//}

package UserInterface;

import DAO.RoomOperations;
import Entities.Student;
import Services.WardenController;

import javax.swing.*;
        import java.awt.*;
        import java.awt.event.ActionEvent;
import java.net.URL;

public class NewStudent extends JFrame {

    private JTextField nameField, aadharField, mobileField, dobField, admissionDateField, genderField, passwordField;
    private JTextArea addressArea;
    private JComboBox<String> roomComboBox;
    private void populateRoomDropdown() {
        RoomOperations roomOps = new RoomOperations();
        java.util.List<String> availableRooms = roomOps.fetchAvailableRooms();

        // Clear the current items in the dropdown
        roomComboBox.removeAllItems();

        // Add a blank option at the top
        roomComboBox.addItem("");

        // Add available rooms to the dropdown
        for (String roomNo : availableRooms) {
            roomComboBox.addItem(roomNo);
        }
    }

    public NewStudent() {
        setTitle("Add New Student");
        setSize(1300, 700);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        // Load background image
        URL imageUrl = getClass().getResource("/UI/h6.jpg");
        ImageIcon backgroundIcon = (imageUrl != null) ? new ImageIcon(imageUrl) : null;

        JLabel backgroundLabel = new JLabel();
        if (backgroundIcon != null) {
            backgroundLabel.setIcon(backgroundIcon);
        } else {
            backgroundLabel.setOpaque(true);
            backgroundLabel.setBackground(Color.LIGHT_GRAY);
        }

        setContentPane(backgroundLabel);
        backgroundLabel.setLayout(new GridBagLayout());

        // Center form panel
        JPanel formPanel = new JPanel();
        formPanel.setPreferredSize(new Dimension(550, 600));
        formPanel.setLayout(new GridBagLayout());
        formPanel.setBackground(new Color(245, 245, 245, 200)); // Light grey with some transparency

        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(10, 10, 10, 10);
        gbc.anchor = GridBagConstraints.WEST;

        // Title
        JLabel titleLabel = new JLabel("Add New Student");
        titleLabel.setFont(new Font("Serif", Font.BOLD, 24));
        titleLabel.setForeground(new Color(60, 60, 60));
        gbc.gridwidth = 2;
        gbc.gridx = 0;
        gbc.gridy = 0;
        formPanel.add(titleLabel, gbc);
        gbc.gridwidth = 1;

        int row = 1;
        nameField = addRow("Name", row++, formPanel, gbc);
        aadharField = addRow("Aadhar No.", row++, formPanel, gbc);
        mobileField = addRow("Mobile No.", row++, formPanel, gbc);
        dobField = addRow("DOB", row++, formPanel, gbc);

        // Address (textarea)
        gbc.gridx = 0;
        gbc.gridy = row;
        JLabel addressLabel = new JLabel("Address");
        addressLabel.setFont(new Font("Arial", Font.BOLD, 16));
        addressLabel.setForeground(Color.DARK_GRAY);
        formPanel.add(addressLabel, gbc);

        gbc.gridx = 1;
        addressArea = new JTextArea();
        addressArea.setFont(new Font("Arial", Font.PLAIN, 15));
        addressArea.setLineWrap(true);
        addressArea.setWrapStyleWord(true);
        JScrollPane scrollPane = new JScrollPane(addressArea);
        scrollPane.setPreferredSize(new Dimension(250, 60));
        formPanel.add(scrollPane, gbc);
        row++;

        admissionDateField = addRow("Admission Date", row++, formPanel, gbc);
        genderField = addRow("Gender", row++, formPanel, gbc);
        passwordField = addRow("Set Password", row++, formPanel, gbc);

        // Room No. as dropdown
        gbc.gridx = 0;
        gbc.gridy = row;
        JLabel roomLabel = new JLabel("Room No.");
        roomLabel.setFont(new Font("Arial", Font.BOLD, 16));
        roomLabel.setForeground(Color.DARK_GRAY);
        formPanel.add(roomLabel, gbc);

        gbc.gridx = 1;
        roomComboBox = new JComboBox<>(new String[]{""});
        roomComboBox.setFont(new Font("Arial", Font.PLAIN, 15));
        roomComboBox.setPreferredSize(new Dimension(250, 30));
        formPanel.add(roomComboBox, gbc);
        populateRoomDropdown();
        row++;

        // Buttons
        gbc.gridx = 0;
        gbc.gridy = row;
        JButton resetBtn = createStyledButton("Reset", this::resetForm);
        formPanel.add(resetBtn, gbc);

        gbc.gridx = 1;
        JButton submitBtn = createStyledButton("Submit", this::handleSubmit);
        formPanel.add(submitBtn, gbc);

        backgroundLabel.add(formPanel);
        setVisible(true);
    }

    private JTextField addRow(String label, int row, JPanel panel, GridBagConstraints gbc) {
        JLabel jLabel = new JLabel(label);
        jLabel.setFont(new Font("Arial", Font.BOLD, 16));
        jLabel.setForeground(Color.DARK_GRAY);

        JTextField textField = new JTextField();
        textField.setFont(new Font("Arial", Font.PLAIN, 15));
        textField.setPreferredSize(new Dimension(250, 30));

        gbc.gridx = 0;
        gbc.gridy = row;
        panel.add(jLabel, gbc);

        gbc.gridx = 1;
        panel.add(textField, gbc);

        return textField;
    }

    private JButton createStyledButton(String text, java.awt.event.ActionListener listener) {
        JButton button = new JButton(text);
        button.setFont(new Font("Arial", Font.BOLD, 14));
        button.setBackground(new Color(255, 140, 0));
        button.setForeground(Color.ORANGE);
        button.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        button.setFocusPainted(false);
        button.setBorder(BorderFactory.createEmptyBorder(10, 20, 10, 20));
        button.addActionListener(listener);
        return button;
    }

    private void resetForm(ActionEvent e) {
        nameField.setText("");
        aadharField.setText("");
        mobileField.setText("");
        dobField.setText("");
        addressArea.setText("");
        admissionDateField.setText("");
        genderField.setText("");
        passwordField.setText("");
        roomComboBox.setSelectedIndex(0);
    }
    private void handleSubmit(ActionEvent e) {
        // Extract data from input fields
        String name = nameField.getText().trim();
        String id = aadharField.getText().trim(); // Assuming 'id' is Aadhar number
        String gender = genderField.getText().trim();
        String dob = dobField.getText().trim();
        String admissionDate = admissionDateField.getText().trim();
        String contactNumber = mobileField.getText().trim();
        String address = addressArea.getText().trim();
        String password = passwordField.getText().trim();
        String selectedRoom = (String) roomComboBox.getSelectedItem();

        // Validate fields
        if (name.isEmpty() || id.isEmpty() || gender.isEmpty() || dob.isEmpty() ||
                admissionDate.isEmpty() || contactNumber.isEmpty() || address.isEmpty() ||
                password.isEmpty() || selectedRoom == null || selectedRoom.trim().isEmpty()) {

            JOptionPane.showMessageDialog(this, "Please fill in all the fields.", "Validation Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Create Student object (assuming your Student constructor is like this)
        Student student = new Student(name, id, gender, dob, admissionDate, contactNumber, address, password, selectedRoom);

        // Call controller method to add the student
        WardenController.addNewStudent(student, this);
    }



    public void openEnrollStudent() {

        SwingUtilities.invokeLater(() -> this.setVisible(true));
    }
}