//package UserInterface;
//
//
//import DAO.StaffOperations;
//import Entities.Staff;
//import Services.StaffController;
//
//import javax.swing.*;
//
///**
// *
// * @author karole
// */
//public class NewStaff extends javax.swing.JFrame {
//
//    /**
//     * Creates new form AddStaff
//     */
//    public NewStaff() {
//        initComponents();
//    }
//
//    /**
//     * This method is called from within the constructor to initialize the form.
//     * WARNING: Do NOT modify this code. The content of this method is always
//     * regenerated by the Form Editor.
//     */
//    @SuppressWarnings("unchecked")
//    // <editor-fold defaultstate="collapsed" desc="Generated Code">
//    private void initComponents() {
//
//        jLabel1 = new javax.swing.JLabel();
//        jTextField1 = new javax.swing.JTextField();
//        jLabel2 = new javax.swing.JLabel();
//        jTextField2 = new javax.swing.JTextField();
//        jLabel3 = new javax.swing.JLabel();
//        jTextField3 = new javax.swing.JTextField();
//        jLabel4 = new javax.swing.JLabel();
//        jTextField4 = new javax.swing.JTextField();
//        jLabel5 = new javax.swing.JLabel();
//        jLabel6 = new javax.swing.JLabel();
//        jTextField5 = new javax.swing.JTextField();
//        jTextField6 = new javax.swing.JTextField();
//        jButton1 = new javax.swing.JButton();
//        jButton2 = new javax.swing.JButton();
//
//        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
//
//        jLabel1.setText("Name ");
//
//        jLabel2.setText("Role");
//
//        jTextField2.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jTextField2ActionPerformed(evt);
//            }
//        });
//
//        jLabel3.setText("Contact");
//
//        jTextField3.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jTextField3ActionPerformed(evt);
//            }
//        });
//
//        jLabel4.setText("Email");
//
//        jLabel5.setText("Address");
//
//        jLabel6.setText("Salary");
//
//        jButton1.setText("Submit");
//        jButton1.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jButton1ActionPerformed(evt);
//            }
//        });
//
//        jButton2.setText("Reset");
//        jButton2.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jButton2ActionPerformed(evt);
//            }
//        });
//
//        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
//        getContentPane().setLayout(layout);
//        layout.setHorizontalGroup(
//                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                        .addGroup(layout.createSequentialGroup()
//                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                                .addGroup(layout.createSequentialGroup()
//                                                        .addGap(114, 114, 114)
//                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
//                                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                                        .addGap(153, 153, 153))
//                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
//                                                        .addContainerGap()
//                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                                        .addGap(127, 127, 127)))
//                                        .addGroup(layout.createSequentialGroup()
//                                                .addGap(123, 123, 123)
//                                                .addComponent(jButton1)
//                                                .addGap(109, 109, 109)))
//                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                        .addComponent(jButton2)
//                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                .addContainerGap(276, Short.MAX_VALUE))
//        );
//        layout.setVerticalGroup(
//                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                        .addGroup(layout.createSequentialGroup()
//                                .addGap(115, 115, 115)
//                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                                        .addComponent(jLabel1)
//                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                .addGap(18, 18, 18)
//                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                                        .addComponent(jLabel2)
//                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                .addGap(26, 26, 26)
//                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                                        .addComponent(jLabel3)
//                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                .addGap(18, 18, 18)
//                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                        .addComponent(jLabel4)
//                                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                .addGap(30, 30, 30)
//                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                                        .addComponent(jLabel5)
//                                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                        .addGroup(layout.createSequentialGroup()
//                                                .addGap(18, 18, 18)
//                                                .addComponent(jLabel6))
//                                        .addGroup(layout.createSequentialGroup()
//                                                .addGap(29, 29, 29)
//                                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
//                                .addGap(45, 45, 45)
//                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                                        .addComponent(jButton1)
//                                        .addComponent(jButton2))
//                                .addContainerGap(83, Short.MAX_VALUE))
//        );
//
//        pack();
//    }// </editor-fold>
//
//    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {
//        // TODO add your handling code here:
//    }
//
//    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {
//        // TODO add your handling code here:
//    }
//
//    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
//        // Retrieve data from text fields
//        String name = jTextField1.getText();
//        String role = jTextField2.getText();
//        String contact = jTextField3.getText();
//        String email = jTextField4.getText();
//        String address = jTextField5.getText();
//        float salary = Float.parseFloat(jTextField6.getText());  // Make sure to handle exceptions for invalid input
//
//        // Create a new Staff object
//        Staff newStaff = new Staff(name, contact, address, email);
//        newStaff.setRole(role);
//        newStaff.setSalary(salary);
//
//        // Call the StaffOperations to add the new staff
//        boolean isAdded = StaffController.addStaff(newStaff,this);
//
//        if (isAdded) {
//            // Success, close the window and show a message
//            JOptionPane.showMessageDialog(this, "Staff added successfully!");
//            this.dispose();  // Close the current frame
//        } else {
//            // Error occurred, show a message
//            JOptionPane.showMessageDialog(this, "Error adding staff. Please try again.");
//        }
//    }
//
//    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
//        jTextField1.setText("");
//        jTextField2.setText("");
//        jTextField3.setText("");
//        jTextField4.setText("");
//        jTextField5.setText("");
//        jTextField6.setText("");
//    }
//
//    public void openEnrollStaff() {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(NewStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(NewStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(NewStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(NewStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new NewStaff().setVisible(true);
//            }
//        });
//    }
//
//    // Variables declaration - do not modify
//    private javax.swing.JButton jButton1;
//    private javax.swing.JButton jButton2;
//    private javax.swing.JLabel jLabel1;
//    private javax.swing.JLabel jLabel2;
//    private javax.swing.JLabel jLabel3;
//    private javax.swing.JLabel jLabel4;
//    private javax.swing.JLabel jLabel5;
//    private javax.swing.JLabel jLabel6;
//    private javax.swing.JTextField jTextField1;
//    private javax.swing.JTextField jTextField2;
//    private javax.swing.JTextField jTextField3;
//    private javax.swing.JTextField jTextField4;
//    private javax.swing.JTextField jTextField5;
//    private javax.swing.JTextField jTextField6;
//    // End of variables declaration
//}
//
package UserInterface;

import Entities.Staff;
import Services.StaffController;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.net.URL;

public class NewStaff extends JFrame {

    private JTextField nameField, roleField, contactField, emailField, salaryField;
    private JTextArea addressArea;

    public NewStaff() {
        setTitle("Add New Staff");
        setSize(1300, 700);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        // Load background image
        URL imageUrl = getClass().getResource("/UI/h6.jpg");
        ImageIcon backgroundIcon = (imageUrl != null) ? new ImageIcon(imageUrl) : null;

        JLabel backgroundLabel = new JLabel();
        if (backgroundIcon != null) {
            backgroundLabel.setIcon(backgroundIcon);
        } else {
            backgroundLabel.setOpaque(true);
            backgroundLabel.setBackground(Color.LIGHT_GRAY);
        }

        setContentPane(backgroundLabel);
        backgroundLabel.setLayout(new GridBagLayout());

        // Centered form panel
        JPanel formPanel = new JPanel();
        formPanel.setPreferredSize(new Dimension(500, 500));
        formPanel.setLayout(new GridBagLayout());
        formPanel.setBackground(new Color(245, 245, 245, 240)); // semi-transparent background

        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(10, 10, 10, 10);
        gbc.anchor = GridBagConstraints.WEST;

        // Title
        JLabel titleLabel = new JLabel("Add New Staff");
        titleLabel.setFont(new Font("Serif", Font.BOLD, 24));
        titleLabel.setForeground(Color.DARK_GRAY);
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridwidth = 2;
        formPanel.add(titleLabel, gbc);
        gbc.gridwidth = 1;

        int row = 1;
        nameField = addRow("Name", row++, formPanel, gbc);
        roleField = addRow("Role", row++, formPanel, gbc);
        contactField = addRow("Contact", row++, formPanel, gbc);
        emailField = addRow("Email", row++, formPanel, gbc);

        // Address textarea
        gbc.gridx = 0;
        gbc.gridy = row;
        JLabel addressLabel = new JLabel("Address");
        addressLabel.setFont(new Font("Arial", Font.BOLD, 16));
        formPanel.add(addressLabel, gbc);

        gbc.gridx = 1;
        addressArea = new JTextArea();
        addressArea.setFont(new Font("Arial", Font.PLAIN, 14));
        addressArea.setLineWrap(true);
        addressArea.setWrapStyleWord(true);
        JScrollPane scrollPane = new JScrollPane(addressArea);
        scrollPane.setPreferredSize(new Dimension(250, 60));
        formPanel.add(scrollPane, gbc);
        row++;

        salaryField = addRow("Salary", row++, formPanel, gbc);

        // Buttons
        gbc.gridx = 0;
        gbc.gridy = row;
        JButton submitBtn = createStyledButton("Submit", this::handleSubmit);
        formPanel.add(submitBtn, gbc);

        gbc.gridx = 1;
        JButton resetBtn = createStyledButton("Reset", this::resetForm);
        formPanel.add(resetBtn, gbc);

        backgroundLabel.add(formPanel);
        setVisible(true);
    }

    private JTextField addRow(String label, int row, JPanel panel, GridBagConstraints gbc) {
        JLabel jLabel = new JLabel(label);
        jLabel.setFont(new Font("Arial", Font.BOLD, 16));
        jLabel.setForeground(Color.DARK_GRAY);

        JTextField textField = new JTextField();
        textField.setFont(new Font("Arial", Font.PLAIN, 15));
        textField.setPreferredSize(new Dimension(250, 30));

        gbc.gridx = 0;
        gbc.gridy = row;
        panel.add(jLabel, gbc);

        gbc.gridx = 1;
        panel.add(textField, gbc);

        return textField;
    }

    private JButton createStyledButton(String text, java.awt.event.ActionListener listener) {
        JButton button = new JButton(text);
        button.setFont(new Font("Arial", Font.BOLD, 18));
        button.setBackground(new Color(70, 130, 180));
        button.setForeground(Color.ORANGE);
        button.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        button.setFocusPainted(false);
        button.setBorder(BorderFactory.createEmptyBorder(10, 20, 10, 20));
        button.addActionListener(listener);
        return button;
    }

    private void resetForm(ActionEvent e) {
        nameField.setText("");
        roleField.setText("");
        contactField.setText("");
        emailField.setText("");
        addressArea.setText("");
        salaryField.setText("");
    }

    private void handleSubmit(ActionEvent evt) {
        // Retrieve data from text fields
        String name = nameField.getText();
        String role = roleField.getText();
        String contact = contactField.getText();
        String email = emailField.getText();
        String address = addressArea.getText();
        float salary = Float.parseFloat(salaryField.getText());  // Make sure to handle exceptions for invalid input

        // Create a new Staff object
        Staff newStaff = new Staff(name, contact, address, email);
        newStaff.setRole(role);
        newStaff.setSalary(salary);

        // Call the StaffOperations to add the new staff
        boolean isAdded = StaffController.addStaff(newStaff, this);

        if (isAdded) {
            // Success, close the window and show a message
            JOptionPane.showMessageDialog(this, "Staff added successfully!");
            this.dispose();  // Close the current frame
        } else {
            // Error occurred, show a message
            JOptionPane.showMessageDialog(this, "Error adding staff. Please try again.");
        }
    }


    public void openEnrollStaff() {
        SwingUtilities.invokeLater(()->this.setVisible(true));

    }
}